name: whatsapp_clone
description: "WhatsApp Clone."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/chat_bg.png
    - assets/flutter_ad.png
    - assets/profile_pic.png
    - assets/Vector(Stroke).png
    - assets/Phone_2.png
    - assets/video.png
    - assets/More-vertical.png
    - assets/Camera.png
    - assets/Send.png
    - assets/Mic.png